# Generated by Django 4.2.20 on 2025-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('rl', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('skills', models.ManyToManyField(blank=True, to='market_analysis.skill')),
            ],
            options={
                'unique_together': {('title', 'company', 'source')},
            },
        ),
    ]
