# Generated by Django 5.1.8 on 2025-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('skills', models.ManyToManyField(blank=True, to='projects.skill')),
            ],
        ),
    ]
