# Generated by Django 5.0.6 on 2025-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MarketData',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='joboffer',
            unique_together={('title', 'company', 'source')},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='market_analysis.skill'),
        ),
    ]
