# Generated by Django 4.2.20 on 2025-04-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0002_rename_rl_joboffer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand_count', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_analysis.skill')),
            ],
            options={
                'unique_together': {('date', 'skill', 'source')},
            },
        ),
    ]
