# Generated by Django 5.0.6 on 2025-04-22 10:46

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0003_marketdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100, unique=True),
        ),
    ]
