# Generated by Django 4.2.20 on 2025-04-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='skills',
            field=models.ManyToManyField(related_name='job_offers', to='market_analysis.skill'),
        ),
    ]
