# Generated by Django 5.0.6 on 2025-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0005_alter_joboffer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_collation='fr-CI-x-icu', max_length=100, unique=True),
        ),
    ]
